### ISSUE TITLE
Since Wed 17/Oct/2018 PAYMENT.SALE.COMPLETED sometimes omitting data.resource.billing_agreement_id

### ISSUE THREAD

**Issue by eliotsykes** [paypal/PayPal-REST-API-issues#274]
### General information

* Environment: Production
* `PayPal-Debug-ID` value: `9d2af352a992` (one example)

### Issue description

Since Wed 17/Oct/2018, 6 out of 86 `PAYMENT.SALE.COMPLETED` webhook events have unexpectedly omitted the `billing_agreement_id` (more accurately the `data["resource"]["billing_agreement_id"]` field). 

(The remaining 80 of 86 `PAYMENT.SALE.COMPLETED` events are as expected as they include the billing_agreement_id).

Has anything changed in the PayPal REST API this week that could explain this?

**Comment by eliotsykes** [comment]
Related to this, it looks like the `Sale` resource has no knowledge of its associated `BillingAgreement` when it should. However the inverse is not true. The `BillingAgreement` *does* know its associated `Sale`.

For example, if I take one of the affected billing agreements:

```ruby
# Put an affected billing_agreement_id here instead:
billing_agreeement_id = 'I-ANONYMISED'

# Get all the transactions associated with this agreement:
transactions = PayPal::SDK::REST::Agreement.transactions(
  billing_agreement_id, '2010-01-01', '2018-10-20'
)

# Get the sale id for the latest transaction (aka transaction_id),
# proving the billing_agreement knows about its sale:
sale_id = transactions.agreement_transaction_list.last.transaction_id

# Look up the Sale:
sale = PayPal::SDK::REST::Sale.find(sale_id)

# Does the sale know its billing agreement? Not when this bug happens:
if sale.billing_agreement_id.nil?
  puts "BUG? The sale does not know its billing agreement id :-("
else
  puts "NO BUG: The sale DOES know its billing agreement id! :-)"
end
```

**Comment by beheh** [comment]
We're observing the same issue at a comparable frequency in our app also since October 17th.

This is a critical issue for us, as we are no longer able to update Billing Agreements (usually from state `Pending` to `Active`) upon receiving an incoming sale.

**Comment by SHELA** [comment]
The same issue. But only today started. Rechecking now every new agreement. Also critical issue for us.

**Comment by eliotsykes** [comment]
Are any PayPal representatives reading this able to confirm/deny this is related to this ongoing incident with IPN first reported on 19th Oct 2018? I'm (possibly wrongly) assuming the REST API is partially dependent on IPN.

> Instant Payment Notification (IPN) issue (PP-LIVE-8498)
> Incident Start: Oct 19, 02:11 UTCIncident End: On-going
> AFFECTED PRODUCTS:
> Notifications
> Initial Notification:
> We're experiencing a system issue impacting the generation of Instant Payment Notifications (IPN) on the production environment. Our technical teams have been engaged and are actively troubleshooting the issue.
> Oct 19, 16:40 UTC

Source: https://www.paypal-status.com/incident/production

**Comment by cmoiccool** [comment]
The paypal status page is now showing the issue as solved since 20 Oct 2018 and i received Sale events with missing Billing Agreement ID on 22 Oct 2018.
Also on the API > REST APIs > Webhooks section on paypal status page it is reporting a steady "Operational" status.

This makes me think that it is not related or paypal have not been able to identify a relation between these two issues.

For now i have had no luck getting response from paypal representatives through this Github repo, only through paypal support, even when support told me i had found a bug in the REST API and had informed the responsible team i got no response on the related issue here, so i would suggest opening a case on paypal support page. They may last a week to respond but at some time they will respond.

And once again i will use IPN as a workaround for this Webhook issue...

**Comment by kslimani** [comment]
Same issue for us, from 19 to 22 Oct. 2018.

But it seems to be fixed  _(for us, it started again to fill the "billing_agreement_id" property  since 2018-10-22 16:13:09 UTC)_.

**Comment by eliotsykes** [comment]
The issue is ongoing, seen a few times today, with the most recent occurrence happening at 2:30pm UTC (Tues 23 Oct 2018).

**Comment by eliotsykes** [comment]
To Paypal support, please do ask if there's any extra details we can provide to assist with this.

(@braebot are you able to advise on whats best to do next?)

**Comment by cmoiccool** [comment]
I have identified that if the execute API call returns an `agreement_details['state']: 'Pending'` then the related `PAYMENT.SALE.COMPLETED` webhook event does not include the Billing Agreement ID, but if the execute API call returns an `agreement_details['state']: 'Active'` then the related `PAYMENT.SALE.COMPLETED` webhook event comes with the Billing Agreement ID.

Before 17 Oct 2018 i did not get any execute API call returning an `agreement_details['state']: 'Pending'` the problem started when the execute call started to sometimes return the Pending State

**Comment by eliotsykes** [comment]
@cmoiccool I'm also seeing something similar. 

Only recently started to see executed agreements in `Pending` state, they used to be only `Active` or `Cancelled`. If the agreement is repeatedly executed, it eventually turns from `Pending` to `Active` or `Cancelled`. It looks like most, if not all, those pending agreements to produce the buggy `PAYMENT.SALE.COMPLETED` webhook events without the billing agreement id.

**Comment by kslimani** [comment]
We are getting again completed Sales without billing agreement id, so i can confirm that the issue is not fixed.

**Comment by eliotsykes** [comment]
Anybody heard from PayPal about this? Are they are treating this as a bug, or its new intended behaviour? 

It'd be helpful to get confirmation, even if it is a bug, and it won't be fixed for some time, that'd be helpful to know. At the moment its tricky to plan ahead. Thanks in advance.

(cc @braebot @randstraw)

**Comment by cmoiccool** [comment]
I confirm that the issue is still happening, and for now the solution i can see is to use IPN instead of Webhooks.
With webhooks, the notifications are decoupled in multiple webhooks but not with IPN.

Webhooks when Billing Agreement execute returns an:

- `Active` state: `BILLING.SUBSCRIPTION.CREATED` then `PAYMENT.SALE.COMPLETED` including Billing Agreement ID - OK to handle

- `Cancelled` state: `BILLING.SUBSCRIPTION.CREATED` then `BILLING.SUBSCRIPTION.CANCELLED` - OK to handle

- `Pending` state: `BILLING.SUBSCRIPTION.CREATED` then `PAYMENT.SALE.COMPLETED` without Billing Agreement ID - Not OK to handle

For the same Billing Agreement you will get theses IPN when execute returns an:

- `Active` state: one IPN of type `recurring_payment_profile_created` with `"initial_payment_status": "Completed"
` and `"initial_payment_txn_id": "XXXXXXXXXXXXXXX"` and `"recurring_payment_id": "I-XXXXXXXXX"` - OK to handle

- `Cancelled` state: one IPN of type `recurring_payment_profile_cancel` with `"initial_payment_status": "Failed"` and `"recurring_payment_id": "I-XXXXXXXXXX"` - OK to handle

- `Pending` state: one IPN of type `recurring_payment_profile_cancel` with `"initial_payment_status": "Failed"` and `"recurring_payment_id": "I-XXXXXXXXXX"` - OK to handle

As you already have to use IPN to be able to handle eCheck payments notifications, recurring payment skipped notifications and recurring payment failed notifications, this is just one more case you have to handle through IPN notifications to be able to handle correctly as Webhook notifications are not yet ready for such cases as identified in #15, #108, #109 and #105

**Comment by meowist** [comment]
Hello @cmoiccool @braebot and all. We've been experiencing this issue since October 20th or so and it persists. We submitted a support ticket to PayPal via their "PayPalTech Support" portal and they replied to confirm that the bug is a known issue (entire reply pasted below). If others submit similar tickets we may get them to focus more attention on this issue:

https://www.paypal-techsupport.com

If anyone has new information or other possible solutions, please share.


---

```
Thank you for the information.  I can now determine you are experiencing a known issue, I have added you to the list of impacted accounts so that this issue can be addressed when the issue is resolved.  This ticket will remain in pending fix until I hear back from our Engineers on the issue.  I will contact you again when more information is available.
```

**Comment by kslimani** [comment]
@eliotsykes @cmoiccool @meowist : we got an answer from PayPal support which is aware of the issue. Their developers are actively working on it.

**Comment by meowist** [comment]
thanks @kslimani. sounds like you got the same reply we did. when did you hear back from them confirming it's a known issue? we heard from them last night (Oct 25)

**Comment by kslimani** [comment]
@meowist we received the answser today on Fri, 26 Oct 2018 07:20:55 -0700 (PDT).

**Comment by meowist** [comment]
thanks @kslimani. I had asked them to "escalate" the issue and this is the latest we heard (pasted below) as of Fri 10/26/2018 11:40 AM EST

> I apologize for any inconvenience this issue is causing you.  I have escalated this issue to our Engineering team for further investigation, there is no further escalation path that can be taken at this time.  Currently, the issue is still being investigated and no specific timeframe has been proved as of yet.  I will update you again when more information is available.

**Comment by cmoiccool** [comment]
@meowist I opened the issue through their new support page https://www.paypal-support.com/ and got the response on Oct 26, 2018 7:30:15 AM:

> We are aware of this issue and we are working to resolve it.  I will research this matter further and update you with more information as it becomes available.

But to be honest, as i knew the support solution would not be so quick, i first added IPN handling to solve the issue and then opened the support ticket. For now it is working with IPN so i will probably stick to it.

**Comment by kslimani** [comment]
We did receive also the same "escalation" answer. We are also using IPN to handle Sales completion.

Basically we disabled `BILLING.SUBSCRIPTION.CREATED` webhook handler and added a new one which listen to `recurring_payment_profile_created` and `recurring_payment` and "transform" it into an `IPN.BILLING.SUBSCRIPTION.CREATED` event _(filling the properties we need)_ to finally use the same handling code.
_(we still store `BILLING.SUBSCRIPTION.CREATED` events to monitor the issue)_

**Comment by cmoiccool** [comment]
I have detected another related problem, if a refund is made for a payment that had the Billing Agreement ID missing on its `PAYMENT.SALE.COMPLETED` , the related `PAYMENT.SALE.REFUNDED` event is not sent, only the IPN with`"payment_status": "Refunded"` is sent.

I think i am really going to go full IPN and forget about handling anything through webhook...

**Comment by meowist** [comment]
Thanks for updates @kslimani and @cmoiccool (and for pointing out the new tech support portal). I actually spoke to someone at PayPal yesterday about the issue and he said, once again, that they have no news and no ETA on a fix. It also sounded like they don't really work weekends, so likely we are looking at Mon-Tues next week at the earliest to have any news on this. 

We are considering moving to IPN as well.

**Comment by kslimani** [comment]
@lewiswilbynm : the issue is still happening for us (2018-10-29).

**Comment by ekleop** [comment]
same for us, Agreement ID is missed for the PAYMENT.SALE.COMPLETED state = Active too. Started from 22-10-2018

**Comment by thomas-dotworx** [comment]
Same issue here

**Comment by AndreyD** [comment]
+
the same problem

**Comment by dyorgio** [comment]
Same problem here :(, somebody can tell me if we will receive another event with billing_agreement_id and how much time to it happens?

**Comment by ekleop** [comment]
@dyorgio 
> Same problem here :(, somebody can tell me if we will receive another event with billing_agreement_id and how much time to it happens?

No, just one event without billing_agreement_id which we cannot link the billing_subscription_create event. So we have to process the payment manually.

**Comment by dyorgio** [comment]
I recently changed my contract to reduce Paypal fees (with 30 days to cash out the money as penalty ), maybe can it be the problem? Anybody did it recently too?

**Comment by meowist** [comment]
@dyorgio I doubt that's the root cause of the problem; we had changed nothing like that and are still having this problem. I spoke to PayPal and they confirmed the problem is a bug on their end. It's now been broken for 13 days and PayPal confirmed to me (as of today) that they have no solution yet.

**Comment by dyorgio** [comment]
Hello guys, I just received another event today without billing_agreement_id from PayPal.
To avoid erros in my payment logic I copy entire body of PayPal original event and included manually billing_agreement_id field with correct value.
I also included no billing_agreement_id handling in my logic if I already processed sale id (I saved it on my database when processed adjusted event), so next time PayPal will receive a 200 response.

**Comment by SHELA** [comment]
> @dyorgio yes I'm sure. We got a lot of "empty" PAYMENT.SALE.COMPLETED events already.
> How did you find the correct billing_agreement_id? We can get 4-5 "BILLING.SUBSCRIPTION.CREATED" events before PAYMENT.SALE.COMPLETED so we cannot link the event to the appropriate BILLING.SUBSCRIPTION.CREATED

We have initial payment for subscription. and after we get notifications about BILLING.SUBSCRIPTION.CREATED we recheck all transactions with biiling_id that we get from BILLING.SUBSCRIPTION.CREATED notify.

**Comment by ekleop** [comment]
PAYMENT.SALE.COMPLETED doesn't have any common id with BILLING.SUBSCRIPTION.CREATED event. It had billing_agreement_id before 22 October but now there isn't

**Comment by albiesoft** [comment]
100% time to move my business somewhere else! Since the 17th of October and they still haven't even let us know what they are doing to fix this! Paypal you are going to lose loads of customers if you keep up this way.

**Comment by dyorgio** [comment]
Hi @ekleop, I just create Agreement BEFORE ask customer for payment. When you do that you receive a new ID (token) and a approval_url to redirect user (in my case I use a new blank tab).
I don't process other events on my webhook, only PAYMENT.SALE.COMPLETED.

**Comment by dyorgio** [comment]
Guys, yesterday I received the same event again, without billing_agreement_id, and, because of my last modifications, now webhook events is green on developer.paypal.com portal, and sale status is COMPLETED.

**Comment by meowist** [comment]
hi @dyorgio @albiesoft @vnlinh112 @ekleop @eliotsykes and all. Just FYI that we got confirmation on Friday 11/02/2018 12:16 PM ET that PayPal engineers are actively working on this problem. They asked us a few questions about our payment flow process, so it seems they are addressing this now. Still not clear when or if they will actually fix it--no ETA or other commitments from PayPal on that.

**Comment by brentd** [comment]
I think I've figured out the basic steps for how reconciliation for these can work:

1. Find all local billing agreements which have not received `PAYMENT.SALE.COMPLETE`.
2. Look at the [billing agreement's transactions](https://developer.paypal.com/docs/api/payments.billing-agreements/v1/#billing-agreements_transactions). This endpoint is a bit annoying because it _requires_ `start_date` and `end_date`, but seems fine to accept a wide date range (e.g. 300 days). I'm using tomorrow's date as the `end_date`.
3. If the billing agreement has completed a payment, you should see both a `status: Created` transaction and a `status: Completed` transaction.
4. This was a lucky discovery because it's undocumented: the completed transaction has a `transaction_id`, **which is the Sale ID**. You can now use this ID to find the Sale [via its GET endpoint](https://developer.paypal.com/docs/api/payments/v1/#sale_get).

**Comment by vnlinh112** [comment]
Agree @brentd, I'm working on changing the workflow too. I let user in even if I have not receive transaction and set `state = Pending` and `expire_date = tomorrow`, then my cronjob (twice a day) will check all the subscription which have `state = Pending`, try to get latest `billing_agreement` to see if there is transaction info. I hope when next transaction is completed, I will receive webhook with `billing_agreement_id`, otherwise I have to write another cronjob to check...

**Comment by meowist** [comment]
Some (tentative) good news to share... we heard from PayPal at 11/05/2018 03:08 PM ET that they are working on a fix for this bug, to be deployed perhaps this week:

> Currently, a fix has been determined and there is a plans to push the fix this week.  I don't have a specific time when yet, but it looks like we are moving forward this week.

**Comment by kor-ea** [comment]
PayPal says it's fixed
The team in charge of this issue deployed a patch that solved the problem
according to our tests. Could you please have a look on your side and
confirm me if you still see the issue or not.

Please apologize us again for the inconvenience caused.



6 нояб. 2018 г. 17:29 пользователь "Justin" <notifications@github.com>
написал:

**Comment by kslimani** [comment]
@kor-ea : we received the same answer from PayPal support.

We noted that billing agreement id seems to be filled in `PAYMENT.SALE.COMPLETED` webhook events since 2018-11-07.

Could someone also confirm this ?

We are still using IPN events for now, and probably switch back to webhook events in a few days if the issue is really fixed.

**Comment by kslimani** [comment]
@eliotsykes if i understand well, you are confirming that the issue is still happening when billing agreement has "Pending" state ?

**Comment by eliotsykes** [comment]
@kslimani No sorry, I'll try to clarify.

The buggy PAYMENT.SALE.COMPLETED webhook events appear fixed, I've seen none.

There's another issue that started on the same day as the buggy webhook events started. This issue is to do with executing agreements coming back as `Pending` and this issue has not been fixed.

**Comment by ekleop** [comment]
`02:14:13 11.09.18 UTC - PAYMENT.SALE.COMPLETED` event has billing_agreement_id, thanks, this event is fixed.
`BILLING.SUBSCRIPTION.CREATED` event still has state = Pending. There is no state = Active for us anymore. 

First we get `BILLING.SUBSCRIPTION.CREATED` with state = Pending, then we get `PAYMENT.SALE.COMPLETED`(billing_agreement_id is always present) event.

**Comment by cmoiccool** [comment]
I confirm that the last missing billing agreement id in a PAYMENT.SALE.COMPLETED i have seen is on Nov 7, 2018.
I also continue getting billing agreements with execution state of `Pending` that may result in a failed setup fee payment or a successful payment.

So now it is behaving in a different form than on my previous comment https://github.com/paypal/PayPal-REST-API-issues/issues/274#issuecomment-432971607

With webhook when an execute returns a `Pending` state in case:

- Payment Succeeds : `BILLING.SUBSCRIPTION.CREATED` then `PAYMENT.SALE.COMPLETED` including Billing Agreement ID - OK to handle - Problem solved

- Payment Fails : `BILLING.SUBSCRIPTION.CREATED` then... no that's all!  `BILLING.SUBSCRIPTION.CANCELLED` is not sent anymore... 

But fortunately IPN is here to solve the issue so with an execute `Pending` state in case : 

- Payment Succeeds : one IPN of type recurring_payment_profile_created with "initial_payment_status": "Completed" and "initial_payment_txn_id": "XXXXXXXXXXXXXXX" and "recurring_payment_id": "I-XXXXXXXXX" - OK to handle

- Payment Fails : one IPN of type recurring_payment_profile_cancel with "initial_payment_status": "Failed" and "recurring_payment_id": "I-XXXXXXXXXX" - OK to handle

So if you first activate your subscription in your system when a Billing Agreement execute returns a `Pending` state, you should be careful on how you handle the payment failure case, especially if you are relying only on webhooks.

As i am now ignoring webhooks (only storing them) and only handling IPN, it has not been too complicated to handle. 

It was easier to handle when the payment was returning an `Active` and a `Cancelled` state right away but i imagine that introducing the `Pending` state enables more payment methods to be used for the setup fee that are not so 'instantaneous' like eCheck for example. I have now seen cases where the setup fee was paid through eCheck and confirmed a few days later (through IPN of course).

**Comment by kslimani** [comment]
Thank you @eliotsykes @ekleop @cmoiccool  for confirmation and clarifications.

@cmoiccool the `BILLING.SUBSCRIPTION.CANCELLED` is not sent even with `max_fail_attempts` set to `1` ?

**Comment by kslimani** [comment]
@cmoiccool indeed, you are correct, we also cancel agreement on setup_fee failure.

**Comment by ed-r4d1cal** [comment]
The issue seems to be fixed now!

**Comment by eliotsykes** [comment]
> However the API behaviour change to do with executing billing agreements and returning them as Pending is still happening (last seen at 2018-11-09 08:48 UTC). Before 17/Oct/2018, executing billing agreements would return only Active or Cancelled state.

Update on the above: since `Mon 12 Nov 2018 17:45:01 UTC`, we've not seen any `Pending` billing agreements. We've only received `Active` and `Cancelled` agreements.

Can anyone else confirm they've stopped getting `Pending` billing agreements?

**Comment by younkim** [comment]
FYI, we have this problem on setup fee's `PAYMENT.SALE.COMPLETED` events. However, Paypal recently responded to our technical support ticket saying this issue has been fixed on webhook events moving forward only. We haven't had any setup fees after that response, so I have not been able to verify yet.

**Comment by jkieberking** [comment]
@eliotsykes we are getting returned billing agreements in a `Pending` state after we execute them every time in our sandbox account.

**Comment by jkieberking** [comment]
> @eliotsykes we are getting returned billing agreements in a `Pending` state after we execute them every time in our sandbox account.

This is still happening

**Comment by jkieberking** [comment]
https://github.com/paypal/PayPal-REST-API-issues/issues/274#issuecomment-439507313

This is still happening

**Comment by IsmaHaro** [comment]
The pending state issue is still ocurring by December 17, 2018.

Is the best option is to use the IPN then?

**Comment by kslimani** [comment]
> The pending state issue is still ocurring by December 17, 2018.
> 
> Is the best option is to use the IPN then?

For this particular event we use IPN as workaround. (we use two webhook handlers : one for rest api events and one for IPN events, which "converts" to rest api format, so the same code is used to process event).

**Comment by IsmaHaro** [comment]
> > The pending state issue is still ocurring by December 17, 2018.
> > Is the best option is to use the IPN then?
> 
> For this particular event we use IPN as workaround. (we use two webhook handlers : one for rest api events and one for IPN events, which "converts" to rest api format, so the same code is used to process event).

Okay great, I'll follow the same path then.
Thanks!

**Comment by Whateverinc** [comment]
has this been resolved? I can't get the billing_agreement_id while working in sandbox.
